import type { Metadata } from "next";
import "./globals.css";
import Provider from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <Provider>
        <body className="font-pretendard-bold m-auto h-fit max-w-[1440px]">
          {children}
          <div id="modal-portal"></div>
        </body>
      </Provider>
    </html>
  );
}
