import type { Metadata } from "next";
import { Navbar } from "@/ui/common/navbar/navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="max-w-[1440px] h-fit m-auto font-pretendard-bold">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
